version: '3'

services:

    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        container_name: wp_mysql
        restart: unless-stopped
        ports:
            - 3309:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wp
        networks: 
            - backend
    
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: wp_php
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: root
            WORDPRESS_DB_NAME: wp
        depends_on: 
            - mysql
        volumes: 
            - .:/var/www/html/wp/
        working_dir: /var/www/html/wp/
        networks: 
            - backend

    nginx:
        image: nginx:latest
        container_name: wp_nginx
        volumes: 
            - .:/var/www/html/wp/
            - ./docker/nginx_log:/var/log/nginx
            - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
            - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
        ports:
            - "9982:80"
        depends_on: 
            - php
        networks: 
            - backend

    phpmyadmin:
        image: phpmyadmin
        container_name: wp_phpmyadmin
        restart: unless-stopped
        ports:
            - 8282:80
        depends_on: 
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=root
            - UPLOAD_LIMIT=64M
        networks: 
            - backend
networks: 
    backend: